### PR TITLE
Convenience method for aligning axis with multipl.

### PR DESCRIPTION
**Pull request by s0mmer**
Needed this variant and I just wanted to make it more convenient. Let me know if there is any reason for why this is not included.

### CODE REVIEW

**Comment by smileyborg** [comment]
Hey Steffen, thanks for this PR. This variant wasn't included because there didn't seem to be any common use case for it. I'm not opposed to adding it at all, but I am curious to know what you were doing that required this.

**Comment by smileyborg** [comment]
BTW, it's interesting that there's another user who also forked and added the same method recently: https://github.com/ovilaro/PureLayout/commit/ee3f7b90b250a42d273f950177f97676874d1766

**Comment by s0mmer** [comment]
Hey Tyler. I experienced the case the other day, where I needed to vertically align a logo in an app. The alignment should have a slight offset. Adding that offset using a constant value in points did not seem like the right solution to me as I wanted to place the logo somewhere on the vertical axis according to the height of the screen and not in points from the center on the vertical axis. Using a multiplier guarantees that the logo will be somehow placed in the same proportionally position on the axis if the height of the screen changes.

Let me know if you would prefer to do this in another way.

**Comment by smileyborg** [comment]
Makes perfect sense to me!

**Pull request merged**
