### PR TITLE
Clairfy description of axis placement

### PR DESCRIPTION
**Pull request by seth-admittedly**
First time using PureLayout and the description of `ALAxisVertical` threw me for a loop. I think this description is slightly clearer.

### CODE REVIEW

**Comment by smileyborg** [comment]
I completely agree after re-reading these :) This has come up a few times over the years, it's very easy once you get it but some small percentage of folks get confused initially.

Of course, a picture is worth a thousand words, so there's a simple illustration linked from the project README too.

Anyways, thanks for suggesting this change!

**Comment by Bogidon** [comment]
Nice, I've been using PureLayout for a while and I still find myself guessing when using `ALAxisVertical`. This is great.

**Comment by smileyborg** [comment]
@Bogidon I feel the same way about `CenterX` and `CenterY`!

**Comment by Bogidon** [comment]
Hm yeah, I can't think of anything more expressive than @seth-admittedly's description. Apple should adopt something more similar 🙏.

**Pull request merged**
