### PR TITLE
Adds Carthage support

### PR DESCRIPTION
**Pull request by chrene**
I created two simple targets so Carthage has something to build.
Lmk what you think

### CODE REVIEW

**Comment by smileyborg** [comment]
Hey Christian, thanks for submitting this PR!

I actually haven't had time to really learn about Carthage yet. I'm obviously familiar with CocoaPods, so let me take some time this weekend to explore Carthage before merging this in.

Generally your changes look good though! I assume you are using Carthage and have tested these already?

**Comment by smileyborg** [comment]
Thanks again for suggesting this. I ended up doing a more extensive re-organization of the repository, and reusing the Xcode project that was holding the demos and unit tests for this purpose. That project is now building two frameworks (one for iOS and one for OS X), which get used by the Example apps, and can also be used by Carthage.

Can you please check out the latest from master and give it a try? Let me know if it's working for you!

**Comment by chrene** [comment]
Hey Smileyborg.

I can checkout the changes for master and make a new pull request if it's something you haven't done yet. Basically it's really simple to add support for carthage. The only thing you need is a shared scheme that builds a framework :)

**Comment by smileyborg** [comment]
@chrene Please see my reply from a couple days ago, the work should be completely done and ready to go in master. Give it a try and let me know.

**Comment by chrene** [comment]
I just did a really basic test

project >  vi Cartfile
   here i just put it > git "..."
project >  carthage update
*** Cloning PureLayout
*** Checking out PureLayout at "v2.0.5"
*** xcodebuild output can be found in /var/folders/nz/wy5yc2bx5d16td9_j2gzkbzw0000gn/T/carthage-xcodebuild.C9zTe5.log
*** Building scheme "PureLayout_iOS" in PureLayout.xcodeproj
*** Building scheme "PureLayout_Mac" in PureLayout.xcodeproj

Sorry for the bad layout here, but it was just easier to copy paste from the terminal. 
It looks like you got it to work. That's great. Now I can use the official repo :D

**Comment by smileyborg** [comment]
Awesome! Thanks again for suggesting this.

**Comment by chrene** [comment]
No Problem. I'm happy I could help.
Thanks for making this great library

**Pull request closed without merging**
